### ISSUE TITLE
Unique code generation

### ISSUE THREAD

**Issue by gvsrepins** [mateusjunges/laravel-invite-codes#12]
**Is your feature request related to a problem? Please describe.**
Make sure the code generated is unique, besides the database.

**Describe the solution you'd like**
Before create a new code, check if it already exists, if so, create a new one in a loop.

**Describe alternatives you've considered**
I have not considered alternatives.

**Additional context**
Maybe I have missed something, but have not seen any place that makes this check before create the new code.
For inspiration you can check this vouchers package for laravel that attacks this same problem: https://github.com/FrittenKeeZ/laravel-vouchers/blob/master/src/Vouchers.php#L139

**Comment by mateusjunges** [comment]
Hi @gvsrepins, i fixed it in #13. It will be merged an release as soon as the tests pass.

Thank you!
