### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by affektde** [mateusjunges/laravel-invite-codes#23]
**Is your feature request related to a problem? Please describe.**
We cannot install the package on PHP8 systems. The necessary entry is missing in `composer.json`.

**Describe the solution you'd like**
Full PHP8 support.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

I will try to fork and test some changes to the code.

**Comment by affektde** [comment]
#24 works in production environment with PHP8.

**Comment by affektde** [comment]
I think we have to drop Laravel 5.8 :-)

**Comment by mateusjunges** [comment]
Closed and released in [1.4.0](https://github.com/mateusjunges/laravel-invite-codes/tree/1.4.0)
