### ISSUE TITLE
Why does this package need PHP 7.4?

### ISSUE THREAD

**Issue by simonschaufi** [mateusjunges/laravel-invite-codes#8]
Could you explain why you need php 7.4? I would be happy if you could also support php 7.2 if there is no special feature hidden that requires php 7.4.

Laravel itself only requires php 7.2

**Comment by mateusjunges** [comment]
Hi @simonschaufi, i built it to use in the company where i work. We use PHP 7.4 to enforce type properties and , so that is why this package require php 7.4 (type properties has been introduced in this version). At this time, i have no intention to downgrade the required php version.

**Comment by simonschaufi** [comment]
Ok. Then I will adjust that in my fork.

**Comment by tobz-nz** [comment]
@simonschaufi could you post a link to your fork here?

**Comment by simonschaufi** [comment]
@tobz-nz I'm currently stuck abroad because of Corona but I will post it when I'm back home. Could take a while though...

**Comment by simonschaufi** [comment]
@tobz-nz there you go: https://github.com/simonschaufi/laravel-invite-codes/tree/php72

**Comment by simonschaufi** [comment]
@mateusjunges I also added some code improvements. Should I make a PR with just those?

**Comment by mateusjunges** [comment]
@simonschaufi yes, send a PR with your changes, but please keep the requirement for php 7.4
